version: "3"
services:
  web:
    build: .
    command: "make dev"
    tty: true
    ports:
      - "3000:3000"
      - "8080:8080"
    volumes:
     - .:/go/src/github.com/s12chung/go_homepage:cached