version: "3"
services:
  web:
    build:
      context: .
      args:
        DOCKER_WORKDIR: $DOCKER_WORKDIR
    tty: true
    env_file:
      - docker.env
    environment:
      AWS_SHARED_CREDENTIALS_FILE: ${DOCKER_WORKDIR}/aws/credentials
      AWS_CONFIG_FILE: ${DOCKER_WORKDIR}/aws/config
    ports:
      - "3000:3000"
      - "8080:8080"